### PR TITLE
Add code annotations for climate reconstruction

### LINKED ISSUE #7: scripts 01 to 04 - annotations + plot GAM outputs
Hi @pratikunterwegs,

Two small tasks:

a) Would you be able to annotate scripts 01-04 in detail so that I can read the code and understand it better?
b) https://github.com/vjjan91/nilgiris-resurvey-project/blob/7f2eee8adbf18309650d2361ab789fe10587d0e4/05_climate-change-analysis.Rmd#L362 - would you be able to visualize the results from L362? (I was playing around with library(mgcviz), but this could be a potential visualization for the supplementary data. 

-all associated data and objects are not up on git for you to reproduce the same.

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This draft PR is a work in progress that aims to fix #7.

I've currently annotated the first two scripts - it's taking a while to remember what each one does. I'm hoping to have this done by Thursay. I'll mark it as a full PR once all the files have been annotated.

### CODE REVIEW

**Comment by vjjan91** [comment]
Thanks Pratik - sounds good!

**Comment by pratikunterwegs** [comment]
@vjjan91 I've finished annotating the scripts 01 - 04.

I haven't found a good visualisation for the climate change model referenced in the issue yet. I haven't read the manuscript yet - will do on the train tomorrow - and will check whether the context suggests anything. One idea I had was to make a heatmap with X axis = year, Y axis = elevation, and showing the % change in the climate variable using colour. Will try that out but might not have all the data locally.

Just a caveat that I'm not sure how much to emphasise this climate change analysis - we're essentially looking for a pattern in data that we have constructed, using arbitrary time-bins and a fairly simple model formulation. I wonder whether this will hold up to scrutiny.

**Comment by pratikunterwegs** [comment]
I guess you could merge this PR, or if you prefer wait until I've tried out the heatmap-type plot. However, I think the maps showing % change relative to the first decadal bin are pretty convincing in showing changes.

**Comment by vjjan91** [comment]
Thanks Pratik - I am still working through the main text and methods. So it's not ready for edits yet, but it should give you an idea of the direction I was thinking. I will go over this code tomorrow before deciding to merge/wait until you have tried exploring the heatmap idea.

**Pull request merged**
